services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www  # Bind-mount Laravel source code
      - ./docker/php/user.ini:/usr/local/etc/php/conf.d/user.ini
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: crm
      DB_USERNAME: user
      DB_PASSWORD: 123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crm_network

  db:
    image: postgres:latest
    container_name: project-management-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - crm_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d crm" ]
      interval: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: project-management-nginx
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - crm_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Web UI
    networks:
      - crm_network

volumes:
  db_data:

networks:
  crm_network:
